development:
  url: localhost:3000
  domain: localhost

test:
  url: localhost:3000
  domain: localhost

production:
  url: 'adc url'
  domain: 'adc domain'
  DATABASE_NAME: gag-system
  DATABASE_USER: gaguser
  DATABASE_PASSWORD: a123456789
